# permissions for end users to view mysqlconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlconfig-viewer-role
rules:
- apiGroups:
  - kubesql.vellanci.gh
  resources:
  - mysqlconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubesql.vellanci.gh
  resources:
  - mysqlconfigs/status
  verbs:
  - get
