# permissions for end users to edit mysqlconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlconfig-editor-role
rules:
- apiGroups:
  - kubesql.vellanci.gh
  resources:
  - mysqlconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubesql.vellanci.gh
  resources:
  - mysqlconfigs/status
  verbs:
  - get
